config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
   # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
    collection { post :import }
    member do
      get 'basic_infomation_edit'
      get 'attendances/edit_one_month'
      patch'attendances/update_one_month'
      get 'attendances/working_users'
      get 'edit_overtime_notice'
      patch 'update_overtime_notice'
      get 'edit_attendance_apply'
      patch 'update_attendance_apply'
      patch 'attendances/update_zokucho_approval'
      get 'edit_zokucho'
      patch 'update_zokucho'
      get 'log_edit'
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
    resources :attendances, only: [:update]
    resources :bases
    
    get 'attendances/:id/edit_overtime', to: 'attendances#edit_overtime', as: :edit_overtime
    patch 'attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime
    
  end
  
  get 'users/:id/show', to: 'users#show_view_only', as: :show_view_only
end

app/models/user.rb
class User < ApplicationRecord
  require 'csv'
  
  has_many :attendances, dependent: :destroy
  has_many :bases, class_name: "Base", dependent: :destroy
  

  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  
  before_save { self.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  validates :basic_work_time, presence: true # 基本時間
  validates :work_time, presence: true # 実労働時間
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  
  
  

  
  has_secure_password      
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  
  
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
     # ダイジェストが存在しない場合はfalseを返して終了します。
     return false if remember_digest.nil?
   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
   # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.import(file)
    if file.present? 
    CSV.foreach(file.path, headers: true, encoding: "Windows-31J:UTF-8") do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
    else
      
     
    end
  end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  # name,    email,       affiliation,employee_number,uid,basic_time,designated_work_start_time,designated_work_end_time,superior,admin,password
  # 濱本　亮,e5@gmail.com,フリーランス,1,1,9:00,10:00,19:00,1,FALSE,password
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy, :log_edit, :show_view_only, :edit_overtime_notice]
  before_action :logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user_only, only: [:show]
  before_action :logged_in_user_only, only: [:show]
  before_action :correct_user, only: :edit   #updateを追加するとusers/index.html.erbの編集が出来なくなる
  before_action :admin_user, only: [:destroy, :index]
  before_action :set_one_month, only: [:show, :log_edit, :show_view_only]

  
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def import
    # fileはtmpに自動で一時保存される
    User.import(params[:file])
    redirect_to users_url
  end
  
  def show
    
    @worked_sum = @attendances.where.not(started_at: nil).count
    @test = Attendance.where.not(finish_schedule_time: nil)
    @approval = @test.where(approval: "申請中")
    # csv出力
    respond_to do |format|
      format.html
      format.csv do
      users_csv
      end
    end  
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user # 保存成功後、ログインします。
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to users_url
    else
      render :edit      
    end
  end
  
  def basic_infomation_edit
    
  end
  
  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}をデータを削除しました。"
    redirect_to users_url
  end
  
  def edit_overtime_notice
    @users = User.all
    @applying_user1 = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-1", approval: "申請中").order(:worked_on)
    @user_s = User.where(id: @applying_user1.pluck(:user_id))
    
    @applying_user_plus = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-2", approval: "申請中").order(:worked_on)
    @user_plus = User.where(id: @applying_user_plus.pluck(:user_id))
  end
  
  def update_overtime_notice
    
    @user = User.find(params[:id])
     overtime_notice_params.each do |id, item|
      attendance = Attendance.find(id)
      attendance.update_attributes!(item)
      at = Attendance.where('change_checkbox = ? or change_checkbox =  ?', false, nil) 
      at.update(approval: "申請中")
     end
     redirect_to @user
  end
  
  #所属長承認モーダル
  
  def edit_zokucho
    @user = User.find(params[:id])
    #上長1の場合
    users = Attendance.where(zokucho_approval: "申請中", zokucho_confirmation: "上長1")
    @users = User.where(id: users.pluck(:user_id))
    #上長2の場合
     users_plus = Attendance.where(zokucho_approval: "申請中", zokucho_confirmation: "上長2")
    @users_plus = User.where(id: users_plus.pluck(:user_id))
    
    @day = users.pluck(:worked_on)
  end
  
  def update_zokucho
     @user = User.find(params[:id])
     shozokucho_params.each do |id, item|
     attendance = Attendance.find(id)
     attendance.update_attributes(item)
     Attendance.where(zokucho_approval: "承認", zokucho_box: nil).update(zokucho_approval: "申請中")
     Attendance.where(zokucho_approval: "否認", zokucho_box: nil).update(zokucho_approval: "申請中")
     Attendance.where(zokucho_approval: "申請中", zokucho_box: true).update(zokucho_box: nil)
     end
     redirect_to user_url(current_user)
  end
  
  # 申請者の勤怠確認
  def show_view_only
    @user = User.find(params[:id])
    @worked_sum = @attendances.where.not(started_at: nil).count
  end
  
 # 勤怠変更モーダル
  def edit_attendance_apply
    @user = User.find(params[:id])
    # 上長1の場合
    @at = Attendance.where(approval_attendance: "申請中", confirmation_attendance: "上長1")
    user_id = @at.pluck(:user_id)
    @users = User.where(id: user_id)
    
    # 上長2の場合
    @at_plus = Attendance.where(approval_attendance: "申請中", confirmation_attendance: "上長2")
    user_id = @at_plus.pluck(:user_id)
    @users_plus = User.where(id: user_id)
  end
 
  def update_attendance_apply
   
   @user = User.find(params[:id])
   after_attendances_application_params.each do |id, item|
     attendance = Attendance.find(id)
     attendance.update_attributes(item)
     if attendance.change_checkbox == true

       
       if attendance.approval_attendance == "承認"
       attendance[:log_approval] = Time.current
       attendance[:started_at] = attendance.after_started_at
       attendance[:finished_at] = attendance.after_finished_at
       attendance[:log_after_started_at] = attendance.after_started_at
       attendance[:log_after_finished_at] = attendance.after_finished_at
       attendance[:log_confirmation] = attendance.confirmation_attendance
       attendance.save
       
       # 申請ログの仕様
      # elsif attendance.approval_attendance == "否認"
       # attendance.update_attributes(log_approval: nil) 
      # elsif attendance.approval_attendance == "申請中"
       # attendance.update_attributes[log_approval: nil]
       
       end
      if attendance.log_started_at.nil?
        attendance[:log_started_at] = attendance.after_started_at
        attendance.save
      end
      if attendance.log_finished_at.nil?
        attendance[:log_finished_at] = attendance.after_finished_at
        attendance.save
      end
     end
     at = Attendance.where(change_checkbox: nil).update(approval_attendance: "申請中")
   end
     redirect_to @user
  end
 
  def log_edit
    @log_approval_users = @user.attendances.where.not(log_approval: nil)
  end
  
 
  private
  
  # CSV出力
  def users_csv
  
    csv_date = CSV.generate do |csv|
      csv_column_names = ["日付","出社時間","退社時間"]
      csv << csv_column_names
      @attendances.each do |attendance|
        
          #started_at と finished_at がnilの日を出力。
        if attendance.started_at.blank? && attendance.finished_at.blank?
          csv_column_values = [
          attendance.worked_on,
          attendance.started_at,
          attendance.finished_at
        ]
        csv << csv_column_values
        end
        
        if attendance.started_at.present? || attendance.finished_at.present?
          if attendance.approval_attendance == "承認"
          csv_column_values = [
            attendance.worked_on,
            attendance.started_at.strftime("%H:%M"),
            attendance.finished_at.strftime("%H:%M")
            ]
            csv << csv_column_values
          elsif attendance.approval_attendance == "否認"
          csv_column_values = [
            attendance.worked_on
            ]
            csv << csv_column_values
          elsif attendance.confirmation_attendance == "上長1" && attendance.approval_attendance == "申請中"
          csv_column_values = [
            attendance.worked_on
            ]
            csv << csv_column_values
          else 
            csv_column_values = [
            attendance.worked_on,
            attendance.started_at.strftime("%H:%M"),
            attendance.finished_at.strftime("%H:%M")
            ]
            csv << csv_column_values
          end
          
          
        end
      end
    end
    send_data(csv_date,filename: "users_test.csv")
    
      
  end
  
  
  def user_params
    params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation, :employee_number, :uid, :basic_time, :basic_work_time, :designated_work_start_time, :designated_work_end_time, :employee_number)
  end
  # 残業申請用
  def overtime_notice_params
    params.require(:user).permit(attendances: [:approval, :change_checkbox])[:attendances]
  end
  # 勤怠申請用
  def after_attendances_application_params
    params.require(:user).permit(attendances: [:approval_attendance, :change_checkbox])[:attendances]
  end
  # 所属長承認用
  def shozokucho_params
    params.require(:user).permit(attendances: [:zokucho_approval, :zokucho_box])[:attendances]
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
  # 勤怠基本情報を指定のフォーマットで返します
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
  
  def format_basic_info_plus(time)
    format("%.2f", (((time.hour * 60) + time.min) / 60.0) + 24.0)
  end
  
  #ログイン中のユーザーidが２or3かを確かめる　superiorユーザーのみ
  def superior_user
    current_user.id == (2 || 3)
  end
  
  #finish_schedule_timeの値を持っている && "Superior User-1"へ申請中のユーザーの数を表示
  def approval_count
    @test = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-1", approval: "申請中")
    @approval_count = @test.count 
  end
  #finish_schedule_timeの値を持っている && "Superior User-2"へ申請中のユーザーの数を表示
  def approval_count_plus
    @test = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-2", approval: "申請中")
    @approval_count = @test.count 
  end
  
  #上長1への勤怠申請の数
  def after_approbal_count
    @at = Attendance.where.not(after_started_at: nil, after_started_at: nil).where(confirmation_attendance: "上長1", approval_attendance: "申請中")
    @at.count
  end
  
  def after_approbal_count_plus
    @at = Attendance.where.not(after_started_at: nil, after_started_at: nil).where(confirmation_attendance: "上長2", approval_attendance: "申請中")
    @at.count
  end
  
  def approval_count_attendance
    @test = Attendance.where.not(finish_schedule_time: nil).where(confirmation_attendance: "上長1", approval_attendance: "申請中")
    @approval_count_attendance = @test.count
  end
  
  # Superior User-1へ申請中のユーザー全てを表示
  def applying_user_superior1
     @applying_user1 = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-1", approval: "申請中")
  end
  
  # Superior User-2へ申請中のユーザー全てを表示
  def applying_user_superior2
     @applying_user2 = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-2", approval: "申請中")
  end
  
  # Superior User-1へ申請中のユーザーの名前を全て表示
  def applying_user_name
    @applying_user1 = Attendance.where.not(finish_schedule_time: nil).where(confirmation: "Superior User-1", approval: "申請中")
    @user = User.where(id: @applying_user1.pluck(:user_id))
  end
  
  def shozokucho_approval_count
    @user = Attendance.where(zokucho_approval: "申請中", zokucho_confirmation: "上長1").count
  end
  
  def shozokucho_approval_count_plus
    @user = Attendance.where(zokucho_approval: "申請中", zokucho_confirmation: "上長2").count
  end
  
end

app/views/users/_edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">基本情報編集</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: @user %>
  
    <%= f.label :name, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :name, class: "form-control" %>
  
    <%= f.label :email, class: "label-#{yield(:class_text)}" %>
    <%= f.email_field :email, class: "form-control" %>
    
    <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
    <%= f.text_field :affiliation, class: "form-control" %>
  
    <%= f.label :password, class: "label-#{yield(:class_text)}" %>
    <%= f.password_field :password, class: "form-control" %>
  
    <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/basic_infomation_edit.html.erb
<h1>ページだけ</h1>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_attendance_apply.js.erb
$("#edit-attendance-apply").html("<%= escape_javascript(render 'edit_attendance_apply') %>");
$("#edit-attendance-apply").modal("show");

app/views/users/edit_basic_info.js.erb
$("#edit-basic-info").html("<%= escape_javascript(render 'edit_basic_info') %>");
$("#edit-basic-info").modal("show");

app/views/users/edit_overtime_notice.js.erb
$("#edit-overtime-notice").html("<%= escape_javascript(render 'edit_overtime_notice') %>");
$("#edit-overtime-notice").modal("show");

app/views/users/edit_zokucho.js.erb
$("#edit-zokucho").html("<%= escape_javascript(render 'edit_zokucho') %>");
$("#edit-zokucho").modal("show");

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>



<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td><%= link_to "⇦前月へ", user_path(date: @first_day.prev_month), class: "btn btn-primary btn-xs" %>
      <%= l(@first_day, format: :middle) %> : 勤怠管理表 : <%= link_to "次月へ", user_path(date: @first_day.next_month), class: "btn btn-primary btn-xs" %>
      </td>
      <td>
        "指定勤務開始時間 : <%= format_basic_info(@user.designated_work_start_time) %>"
        <br>
        "指定勤務終了時間 : <%= format_basic_info(@user.designated_work_end_time) %>"
      </td>
      <td colspan="3">基本時間 : <%= format_basic_info(@user.basic_work_time) %></td>
      <td>初日 : <%= l(@last_day, format: :short) %></td>
      
    </tr>
    
    <tr>
      <td>所属 : <%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名 : <%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数 : <%= @worked_sum %></td>
      <td>締め : <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<!-- superior_user_1の場合 -->
<% if current_user.id == 2 %>
  <% if @test.present? && @test.where(confirmation: "Superior User-1", approval: "申請中") && approval_count > 0 %> <!-- 終了予定時間の値を持っている & 残業申請中の数が0より上ならtrueを返す -->
    <p><%= link_to "【残業申請のお知らせ】", edit_overtime_notice_user_path(@user), remote: true, class: "overtime_class" %><span class="span_class"><%= "#{approval_count}件の通知があります" %></span></p>
  <% else %>
    <p>【残業申請のお知らせ】</p>
  <% end %>
  
  <% if after_approbal_count > 0 %>
   <p><%= link_to "【勤怠申請のお知らせ】", edit_attendance_apply_user_path(@user), remote: true, class: "overtime_class" %><span class="span_class"><%= "#{after_approbal_count}件の通知があります" %></span></p>
  <% else %>
    <p>【勤怠申請のお知らせ】</p>
  <% end %>
  
  <% if shozokucho_approval_count > 0 %>
    <p><%= link_to "【所属長承認申請のお知らせ】", edit_zokucho_user_path(@user), remote: true, class: "overtime_class" %><span class="span_class"><%= "#{ @user = Attendance.where(zokucho_approval: "申請中", zokucho_confirmation: "上長1").count}件の通知があります" %></span></p>
  <% else %>
    <p>【所属長承認申請のお知らせ】</p>
  <% end %>
<% end %>

<!-- superior_user_2の場合 -->
<% if current_user.id == 3%>
  <% if @test.present? && @test.where(confirmation: "Superior User-2", approval: "申請中") && approval_count_plus > 0 %> <!-- 終了予定時間の値を持っている & 残業申請中の数が0より上ならtrueを返す -->
    <%= link_to "【残業申請のお知らせ】", edit_overtime_notice_user_path(date: @user_plus), remote: true, class: "overtime_class" %><span class="span_class"><%= "#{approval_count_plus}件の通知があります" %></span>
  <% else %>
    <p>【残業申請のお知らせ】</p>
  <% end %>
  
  <% if after_approbal_count_plus > 0 %>
   <p><%= link_to "【勤怠申請のお知らせ】", edit_attendance_apply_user_path(@user), remote: true, class: "overtime_class" %><span class="span_class"><%= "#{after_approbal_count_plus}件の通知があります" %></span></p>
  <% else %>
    <p>【勤怠申請のお知らせ】</p>
  <% end %>
  
  <% if shozokucho_approval_count_plus > 0 %>
    <p><%= link_to "【所属長承認申請のお知らせ】", edit_zokucho_user_path(@user), remote: true, class: "overtime_class" %><span class="span_class"><%= "#{ @user = Attendance.where(zokucho_approval: "申請中", zokucho_confirmation: "上長2").count}件の通知があります" %></span></p>
  <% else %>
    <p>【所属長承認申請のお知らせ】</p>
  <% end %>
<% end %>

<p>
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "勤怠修正ログ(承認済)", log_edit_user_path, class: "btn btn-primary" %>
<% if current_user.attendances.where(worked_on: @first_day, zokucho_approval: "承認").present? %>
  <%= link_to "CSV出力", user_path(format: :csv, date: @first_day), class: "btn btn-primary" %>
<% else %>
  <a class="btn btn-primary btn-csv-export disabled">CSV出力</a>
<% end %>
</p>

<div>
  <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
    <thead>
      <tr>
        <td rowspan="3">残業申請</td>
        <td rowspan="3">日付</td>
        <td rowspan="3">曜日</td>
        <td colspan="8">実績</td>
        <td colspan="5">所定外勤務</td>
      </tr>
      <tr>
        <td colspan="3">出社</td>
        <td colspan="3">退社</td>
        <td rowspan="2">在社時間</td>
        <td rowspan="2">備考</td>
        <td colspan="2">終了予定時間</td>
        <td rowspan="2">時間外時間</td>
        <td rowspan="2">業務処理内容</td>
        <td rowspan="2">指示者確認㊞</td>
      </tr>
      <tr>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
        <td></td>
        <td>時</td>
        <td>分</td>
        
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.order(:worked_on).each do |day| %>
        <tr>
          <td><%= link_to "残業申請", user_edit_overtime_path(current_user, day, params: { day: day.worked_on, wday: $days_of_the_week[day.worked_on.wday] }), remote: true, class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= day.started_at.hour if day.started_at.present? %></td>
          <td><%= day.started_at.min if day.started_at.present? %></td>
          <td>
            <% if (Date.current == day.worked_on) && day.started_at.nil? %>
              <%= link_to "出勤登録", user_attendance_path(current_user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= day.finished_at.hour if day.finished_at.present? %></td>
          <td><%= day.finished_at.min if day.finished_at.present? %></td>
          <td>
            <% if (Date.current == day.worked_on) && day.started_at.present? && day.finished_at.nil? %>
              <%= link_to "退勤登録", user_attendance_path(current_user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td>
            <% if day.tomorrow? %>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= str_times = working_times_plus(day.started_at, day.finished_at) %>
                <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <% end %>
            <% else %>
              <% if day.started_at.present? && day.finished_at.present? %>
                <%= str_times = working_times(day.started_at, day.finished_at) %>
                <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
              <% end %>
            <% end %>
          </td>
          <td><%= day.after_note %></td>
          <td><%= day.finish_schedule_time.hour if day.finish_schedule_time.present? %></td> <!-- 終了予定時間 : 時 -->
          <td><%= day.finish_schedule_time.min if day.finish_schedule_time.present? %></td> <!-- 終了予定時間 : 分 -->
          <% if day.tomorrow? %>
            <td><%= format_basic_info_plus(day.finish_schedule_time).to_f - format_basic_info(current_user.designated_work_end_time).to_f if day.finish_schedule_time.present? && current_user.designated_work_end_time.present? %></td>
         
          <% else %>
            <td><%= format_basic_info(day.finish_schedule_time).to_f - format_basic_info(current_user.designated_work_end_time).to_f if day.finish_schedule_time.present? && current_user.designated_work_end_time.present? %></td>
          <% end %>
           
          <td><%= day.business_process %></td> <!-- 業務処理内容 -->
          <td>
            <%= "残業:#{day.approval}:#{name_change(day.confirmation)}" if day.confirmation.present? %><br>
            <%= "勤怠:#{day.approval_attendance}:#{day.confirmation_attendance}" if day.approval_attendance.present? && day.confirmation_attendance == "上長1" %>
            <%= "勤怠:#{day.approval_attendance}:#{day.confirmation_attendance}" if day.approval_attendance.present? && day.confirmation_attendance == "上長2" %>
          </td> <!-- 指示者確認㊞ -->
        </tr>
        <% end %>
    </tbody>
    
    
    <tfoot>
         
      
        <tr>
          <td colspan="2"></td><!--総合勤務時間表示-->
          <td colspan="6"></td>
          <td></td>
          <td>在社合計時間 : <%= format("%.2f", @total_working_times.to_f) %></td>
          <td colspan="5"></td>
          <td>
            <%= form_for(current_user, url: attendances_update_zokucho_approval_user_path(date: @first_day), method: :patch) do |f| %>
              
              <%= f.fields_for :attendances do |attendance| %>
                  所属長承認 : <%= current_user.attendances.find_by(worked_on: @first_day).zokucho_confirmation %><br>
                  <% if current_user.attendances.find_by(worked_on: @first_day).zokucho_approval.present? %>
                    <%= current_user.attendances.find_by(worked_on: @first_day).zokucho_approval %> <br>
                  <% else %>  
                    未申請<br>
                  <% end %>
                <% if current_user.id == 2 %>
                  <%= attendance.select :zokucho_confirmation, [name_change('Superior User-2')], include_blank: true %><br>
                <% else %>
                  <%= attendance.select :zokucho_confirmation, [name_change('Superior User-1')], include_blank: true %><br>
                <% end %>
              <% end %>
             
             <%= f.submit "申請", class: "btn btn-primary" %>
           <% end %>
          </td>
        </tr>
    
    </tfoot>
  </table>
</div>

<%= link_to "基本情報編集", edit_basic_info_user_path(current_user), remote: true, class: "btn btn-success" %>
<!--モーダルウインドウ表示-->

<div id="edit-overtime" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--残業申請-->
<div id="edit-overtime-notice" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--勤怠申請-->
<div id="edit-attendance-apply" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--所属長承認申請-->
<div id="edit-zokucho" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<div id="edit-basic-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>