config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
   # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
    collection { post :import }
    member do
      get 'basic_infomation_edit'
      get 'attendances/edit_one_month'
      patch'attendances/update_one_month'
      get 'attendances/working_users'
      get 'edit_overtime_notice'
      patch 'update_overtime_notice'
      get 'edit_attendance_apply'
      patch 'update_attendance_apply'
      patch 'attendances/update_zokucho_approval'
      get 'edit_zokucho'
      patch 'update_zokucho'
      get 'log_edit'
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
    resources :attendances, only: [:update]
    resources :bases
    
    get 'attendances/:id/edit_overtime', to: 'attendances#edit_overtime', as: :edit_overtime
    patch 'attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime
    
  end
  
  get 'users/:id/show', to: 'users#show_view_only', as: :show_view_only
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  
  validate :started_at_than_finished_at_fast_if_invalid
  
  validates :worked_on, presence: :true
  validates :note, length: { maximum: 50 }
  
 
  
  # 出勤時間が存在しない場合、退勤時間は無効
  validate :finished_at_is_invalid_without_a_started_at
  
   # 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効
  validate :started_at_than_finished_at_fast_if_invalid
  
  validate :finish_schedule_time_validate 
  validate :after_finished_at_nesessary
  validate :finished_at_is_invalid_without_a_started_at
  validate :confirmation_attendance_validate
  # validate :confirmation_attendance_validate_plus
  validate :test_test

  def finish_schedule_time_validate
    if finish_schedule_time.present? && user.designated_work_end_time.present? && !tomorrow?
      errors.add(:finish_work_time, "より早い終了予定時間は無効です") if finish_schedule_time.to_i < user.designated_work_end_time.to_i
    end
  end
  
  def after_finished_at_nesessary
    if after_started_at.present? && after_finished_at.blank?
      errors.add(:after_finished_at, "が必要です") 
    end
  end
  
  
  def finished_at_is_invalid_without_a_started_at
    errors.add(:after_started_at, "が必要です") if after_started_at.blank? && after_finished_at.present?
  end
  
  def started_at_than_finished_at_fast_if_invalid
    if (after_started_at.present? && after_finished_at.present?) && !tomorrow?
      errors.add(:after_started_at, "より早い退勤時間は無効です") if after_started_at > after_finished_at
    end
  end
  
  def confirmation_attendance_validate
   if after_started_at.blank? && after_finished_at.blank?
     if confirmation_attendance.present?
     errors.add(:confirmation_attendance, "が必要です")
     end
   end
  end
  
  def confirmation_attendance_validate_plus
   if after_started_at.present? && after_finished_at.present?
     if confirmation_attendance == ""
     errors.add(:confirmation_attendance, "が必要です")
     end
   end
  end
  
  def test_test
    # strftimeで"時","分"だけのデータを取得して > で比較。strftimeで指定していないと日付の情報まで入ってしまうのでおかしくなる。
    # designated_work_end_time はdefaultで2019/12/01,17:00になっている。
    # tomorrowはチェックが入っていた場合の時間に対応する為に定義。
    if finish_schedule_time.present? && user.designated_work_end_time.present?
      if (user.designated_work_end_time.strftime("%H:%M") > finish_schedule_time.strftime("%H:%M")) && !tomorrow? 
        errors.add(:designated_work_end_time, "より早い終了予定時間は無効です")
      end
    end
  end
  
  
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_user, only: [:edit_one_month, :update_one_month, :working_users]
  before_action :logged_in_user, only: [:update, :edit_one_month]
  before_action :admin_user, only: [:working_users]
  before_action :admin_or_correct_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :set_one_month, only: [:edit_one_month, :working_users, :edit_zokucho]
  
  
  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
     # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0))
        @attendance.update_attributes(log_started_at: Time.current.change(sec: 0))
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0))
        @attendance.update_attributes(log_finished_at: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end
  
  def working_users
    @attendance = Attendance.where.not(started_at: nil).where(finished_at: nil)
  end
  
  # 勤怠編集画面
  def edit_one_month
     @user = User.find(params[:id])
  end
  
  def update_one_month
    @user = User.find(params[:id])
    ActiveRecord::Base.transaction do # トランザクションを開始します。
      after_attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        unless params[:user][:attendances][attendance.id.to_s][:confirmation_attendance].blank?
          attendance.update_attributes!(item)
          if attendance.tomorrow?
            attendance.after_finished_at.tomorrow if attendance.after_finished_at.present?
            attendance.update_attributes(approval_attendance: "申請中")
          else
            attendance.update_attributes(approval_attendance: "申請中")
            attendance
          end
        else
          flash[:info] = "注意:指示者確認が空欄の日付は更新されません"
        end  
      end
    end
     flash[:success] = "1ヶ月分の勤怠情報を申請しました。"
     redirect_to user_url(date: params[:date])
  rescue ActiveRecord::RecordInvalid # トランザクションによるエラーの分岐です。
     flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
     redirect_to attendances_edit_one_month_user_url(date: params[:date])
  end
  
  
    # 残業申請

  def edit_overtime
    @attendance = Attendance.find(params[:id])
    @user = User.find(params[:user_id])
    @superior = User.where(id: [2, 3])
    @day = Date.parse(params[:day])
    @wday = (params[:wday])
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
  end
  
  def update_overtime
     @user = current_user
     @attendance = Attendance.find(params[:id])
     if @attendance.update_attributes(overtime_params)
       @attendance.update_attributes(approval: "申請中")
       @attendance.update_attributes(change_checkbox: "false")
       flash[:success] = "申請しました。"
       redirect_to @user
     else
       flash[:danger] = "無効なデータがありました。"
       redirect_to @user
     end
  end

  
  def update_zokucho_approval #所属長承認申請用
   @user = User.find(params[:id])
   @user.attendances.update(shozokucho_params)
     if @user.attendances.find_by(worked_on: params[:date]).zokucho_confirmation == "上長1" || @user.attendances.find_by(worked_on: params[:date]).zokucho_confirmation == "上長2"
      @user.attendances.where(worked_on: params[:date]).update(zokucho_approval: "申請中")
      @user.attendances.where(worked_on: params[:date]).update(zokucho_day: params[:date])
       flash[:success] = "1ヶ月分の勤怠情報を申請しました。"
       redirect_to @user
     else
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to user_url(date: params[:date])
     end
  end

  private
  
  # 1ヶ月分の勤怠情報を扱います。
  def attendances_params
    params.require(:user).permit(attendances: [:started_at, :finished_at, :note, :log_started_at, :log_finished_at])[:attendances]
  end
  
  def overtime_params
    params.require(:attendance).permit(:finish_schedule_time, :business_process, :tomorrow, :confirmation)
  end
  
  def after_attendances_params
    params.require(:user).permit(attendances: [:after_started_at, :after_finished_at, :after_note, :tomorrow, :approval_attendance, :confirmation_attendance])[:attendances]
  end
  
   # 所属長承認用
  def shozokucho_params
    params.require(:user).permit(attendances: [:zokucho_confirmation])[:attendances]
  end
  
  # beforeフィルター

  # 管理権限者、または現在ログインしているユーザーを許可します。
  def admin_or_correct_user
      @user = User.find(params[:user_id]) if @user.blank?
    unless current_user?(@user) || current_user.admin?
      flash[:danger] = "編集権限がありません。"
      redirect_to(root_url)
    end  
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  
  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  def working_times_plus(start, finish)
    format("%.2f", (((finish.tomorrow - start) / 60) / 60.0))
  end
  
  def name_change(superior_name)
    if superior_name == "Superior User-2"
      superior_name = "上長2"
    elsif
      superior_name == "Superior User-1"
      superior_name = "上長1"
    end
  end
  
end

app/views/attendances/_edit_overtime.html.erb
<% provide(:class_text, 'overtime') %>
<% provide(:button_text, '残業を申請する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">残業申請</h1>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <%= form_with(model: [@user, @attendance], url: user_update_overtime_path(@user, @attendance), local: true, method: :patch) do |f| %>
          <table class="table table-bordered table-striped">
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認</th>
                </tr>
              </thead>
              <tbody>
                  <tr>
                    <td><%= l(@day, format: :short) %></td>
                    <td><%= @wday %></td>
                    <td><%= f.datetime_select :finish_schedule_time, {discard_year: true, discard_month: true, discard_day: true, minute_step: 15}, {class: "form-control datetime_select-class"} %></td>
                    
                    <td><%= f.check_box :tomorrow %></td>
                    <td><%= f.text_field :business_process, class: "form-control" %></td>
                    <% if current_user.id == 2 %>
                      <td><%= f.select :confirmation, ['Superior User-2'] %></td>
                    <% elsif current_user.id == 3 %>  
                      <td><%= f.select :confirmation, ['Superior User-1'] %></td>
                    <% else %>
                      <td><%= f.select :confirmation, @superior.pluck(:name) %></td>
                    <% end %>
                  </tr>
              </tbody>
          </table>
            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
                <button type="button" class="btn btn-default btn-<%= yield(:class_text) %>" data-dismiss="modal">
                  キャンセル
                </button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>

<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
<div>
  <h1>勤怠情報編集</h1>
  <table class="table table-bordered table-condensed table-hover table-striped" id="table-attendances">
    <thead>
      <tr>
        <th>日付</th>
        <td>曜日</td>
        <td>出社</td>
        <td>退社</td>
        <td>翌日</td>
        
        <td>備考</td>
        <td>指示者確認㊞</td>
      </tr>
    </thead>
    
    <tbody>
      <% @attendances.each do |day| %>
        <%= f.fields_for "attendances[]", day do |attendance| %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td><%= $days_of_the_week[day.worked_on.wday] %></td>
         
          <% if !current_user.admin? && (Date.current < day.worked_on)  %>
            <td><%= day.started_at.strftime("%H:%M") + " →" if day.started_at.present? %><%= attendance.time_field :after_started_at, class: "form-control" %></td>
            <td><%= day.finished_at.strftime("%H:%M") + " →" if day.started_at.present? %><%= attendance.time_field :after_finished_at, class: "form-control" %></td>
          <% else %>
            <td><%= day.started_at.strftime("%H:%M") + " →" if day.started_at.present? %><%= attendance.time_field :after_started_at, class: "form-control" %></td>
            <td><%= day.finished_at.strftime("%H:%M") + " →" if day.finished_at.present? %><%= attendance.time_field :after_finished_at, class: "form-control" %></td>
          <% end %>
    
            <td><%= attendance.check_box :tomorrow %></td>
            
          <td><%= attendance.text_field :note, class: "form-control" %></td>
          <% if current_user.id == 2 %>
            <td><%= attendance.select :confirmation_attendance, [name_change('Superior User-2')], include_blank: true, selected: nil %></td>
          <% else %>
            <td><%= attendance.select :confirmation_attendance, [name_change('Superior User-1')], include_blank: true, selected: nil %></td>
          <% end %>  
          
          
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

<div class="center">
  <%= f.submit "まとめて申請", class: "btn btn-lg btn-primary" %>
  <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
</div>
<% end %>

app/views/attendances/edit_overtime.js.erb
$("#edit-overtime").html("<%= escape_javascript(render 'edit_overtime') %>");
$("#edit-overtime").modal("show");

app/views/attendances/working_users.html.erb
<h1>出勤社員一覧</h1>


<table class="table-bordered table-striped table-condensed">
  <thead>
    <tr>
      <th>社員番号</th>
      <th>名前</th>
    </tr>
  </thead>
  <tbody>
    <% @attendance.each do |attendance| %>
      <% User.where(id: attendance.user_id).each do |user|  %>
        <tr>
          <th><%= user.employee_number %></th>
          <th><%= user.name %></th>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>