config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
   # ログイン機能
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users do
    collection { post :import }
    member do
      get 'basic_infomation_edit'
      get 'attendances/edit_one_month'
      patch'attendances/update_one_month'
      get 'attendances/working_users'
      get 'edit_overtime_notice'
      patch 'update_overtime_notice'
      get 'edit_attendance_apply'
      patch 'update_attendance_apply'
      patch 'attendances/update_zokucho_approval'
      get 'edit_zokucho'
      patch 'update_zokucho'
      get 'log_edit'
      get 'edit_basic_info'
      patch 'update_basic_info'
    end
    resources :attendances, only: [:update]
    resources :bases
    
    get 'attendances/:id/edit_overtime', to: 'attendances#edit_overtime', as: :edit_overtime
    patch 'attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime
    
  end
  
  get 'users/:id/show', to: 'users#show_view_only', as: :show_view_only
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Attendance App", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "トップへ", root_path %></li>

            <% unless logged_in? %>
              <li><%= link_to "ログイン", login_path %></li>
            <% end %>
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "ユーザー一覧", users_path %></li>
            
              <li><%= link_to "出勤社員一覧", attendances_working_users_user_path(current_user) %></li>
              <li><%= link_to "拠点情報の修正", user_bases_path(current_user) %></li>
              <li><%= link_to "基本情報の更新", basic_infomation_edit_user_path(current_user) %></li>
            
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account<b class="caret"></b>
                </a>
              <ul class="dropdown-menu">
                <li><%= link_to "設定", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
              </li>
           <% elsif logged_in? %>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account<b class="caret"></b>
                </a>
              <ul class="dropdown-menu">
                <li><%= link_to "勤怠情報", user_path(current_user) %></li>
                <li><%= link_to "設定", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              </ul>
              </li>
           <% end %>
            
              
            
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>